### ISSUE TITLE
HTTP error

### ISSUE THREAD

**Issue by Rocologo** [BtoBastian/bStats#13]
Hi I have just added bStats in my plugin MobHunting and it works. (most of the time) :-)

BUT once in a while I get this HTTP error.

`[MobHunting] Could not submit plugin stats of MobHunting
javax.net.ssl.SSLException: Received fatal alert: internal_error
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208) ~[?:1.8.0_121]
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154) ~[?:1.8.0_121]
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2023) ~[?:1.8.0_121]
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1125) ~[?:1.8.0_121]
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375) ~[?:1.8.0_121]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403) ~[?:1.8.0_121]
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387) ~[?:1.8.0_121]
	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559) ~[?:1.8.0_121]
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185) ~[?:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316) ~[?:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291) ~[?:1.8.0_121]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250) ~[?:1.8.0_121]
	at org.bStats.Metrics.sendData(Metrics.java:278) ~[MobHunting-4.3.7-SNAPSHOT-Bnull.jar:?]
	at org.bStats.Metrics.access$200(Metrics.java:26) ~[MobHunting-4.3.7-SNAPSHOT-Bnull.jar:?]
	at org.bStats.Metrics$2.run(Metrics.java:237) [MobHunting-4.3.7-SNAPSHOT-Bnull.jar:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_121]
`

**Comment by BtoBastian** [comment]
Hey, when has the error occurred?
The last downtime of bStats was on the 21th of January.

**Comment by games647** [comment]
>SSLException: Received fatal alert: internal_error

Check your java installation or update it. I think it has something to do with Cloudflare SSL certificates. Some users of mine plugins had those issues with other Cloudflare websites too. Updating Java fixed it.

**Comment by Rocologo** [comment]
My java is updated, but I only see this error on my test server which is my desktop computer and it runs openjdk.

openjdk version "1.8.0_121"
OpenJDK Runtime Environment (build 1.8.0_121-8u121-b13-0ubuntu1.16.04.2-b13)
OpenJDK 64-Bit Server VM (build 25.121-b13, mixed mode)

My real server runs Oracle Java 8 - also updated, I will immediately install the snapshot and see if the error is there too.

**Comment by Rocologo** [comment]
I have noticed that 

I can see my plugin data
https://bstats.org/plugin/bukkit/MobHunting

But is is missing in the plugin list
https://bstats.org/plugin-list

?

**Comment by Rocologo** [comment]
It seems to work on my real server mc.lindegaard.one where I use Oracle Java 8

root@fractal:~# java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
root@fractal:~#
