### ISSUE TITLE
ExceptionInInitializerError

### ISSUE THREAD

**Issue by grisstyl** [BtoBastian/bStats#69]
```
if (getConfig().getBoolean("metrics", true)) {
            Metrics metrics = new Metrics(this);

            metrics.addCustomChart(new Metrics.SimplePie("characters", () -> String.valueOf(pluginConfig.getInt("characters"))));
        }
```

in the onEnable method gives me an ExceptionInInitializerError.

```
[09:34:54 ERROR]: Error occurred while enabling Characters v3.1.0 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.tripixelstudios.highchrisben.characters.CharactersPlugin.onEnable(CharactersPlugin.java:69) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:380) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:329) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.1.jar:git-Spigot-65e8124-963b19c]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_144]
Caused by: java.lang.IllegalStateException: bStats Metrics class has not been relocated correctly!
        at org.bstats.bukkit.Metrics.<clinit>(Metrics.java:47) ~[?:?]
        ... 12 more
```

Line 69 is the initialization of the Metrics.

**Comment by DoNotSpamPls** [comment]
Read the [tutorial on including bStats Metrics](https://bstats.org/getting-started/include-metrics) **very carefully**. You have missed the step where you need to relocate the classes to a package different from the org.bstats one.

**Comment by grisstyl** [comment]
@DoNotSpamPls Well, I was shading the JAR in, not relocating it manually and I believe I did so correctly in my pom. Following the manual instructions worked fine though. Thanks!
